github: [muhammad-fiaz]
custom: ['https://pay.muhammadfiaz.com']
# Uncomment and fill these if you use other platforms:
# patreon:
# open_collective:
# ko_fi:
# tidelift:
# community_bridge:
# liberapay:
# issuehunt:
# lfx_crowdfunding:
# polar:
# buy_me_a_coffee:
# thanks_dev:
